In [3]:
import torch
import matplotlib.pyplot as plt
import torch.nn.functional as F
%matplotlib inline

Matplotlib is building the font cache; this may take a moment.


In [8]:
words = open('names.txt', 'r').read().splitlines()

In [14]:
chars = sorted(list(set(''.join(words))))
stoi = {s: i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [50]:
#buildint the training dataset
block_size = 3
X, Y = [], []

for w in words[:5]:
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)

In [53]:
Y.shape

torch.Size([32])

In [55]:
C = torch.randn((27,2))
emb = C[X]

In [56]:
emb

tensor([[[-1.4021, -0.2137],
         [-1.4021, -0.2137],
         [-1.4021, -0.2137]],

        [[-1.4021, -0.2137],
         [-1.4021, -0.2137],
         [ 0.5353,  1.1650]],

        [[-1.4021, -0.2137],
         [ 0.5353,  1.1650],
         [-0.1089, -0.7523]],

        [[ 0.5353,  1.1650],
         [-0.1089, -0.7523],
         [-0.1089, -0.7523]],

        [[-0.1089, -0.7523],
         [-0.1089, -0.7523],
         [ 1.2435, -1.3394]],

        [[-1.4021, -0.2137],
         [-1.4021, -0.2137],
         [-1.4021, -0.2137]],

        [[-1.4021, -0.2137],
         [-1.4021, -0.2137],
         [-0.8702,  2.3228]],

        [[-1.4021, -0.2137],
         [-0.8702,  2.3228],
         [ 0.0471,  0.4526]],

        [[-0.8702,  2.3228],
         [ 0.0471,  0.4526],
         [ 0.1257,  0.9819]],

        [[ 0.0471,  0.4526],
         [ 0.1257,  0.9819],
         [-1.4675, -0.3574]],

        [[ 0.1257,  0.9819],
         [-1.4675, -0.3574],
         [ 0.1257,  0.9819]],

        [[-1.4675, -0

In [60]:
torch.cat([emb[:,0,:], emb[:,1,:], emb[:,2,:]], 1)


tensor([[-1.4021, -0.2137, -1.4021, -0.2137, -1.4021, -0.2137],
        [-1.4021, -0.2137, -1.4021, -0.2137,  0.5353,  1.1650],
        [-1.4021, -0.2137,  0.5353,  1.1650, -0.1089, -0.7523],
        [ 0.5353,  1.1650, -0.1089, -0.7523, -0.1089, -0.7523],
        [-0.1089, -0.7523, -0.1089, -0.7523,  1.2435, -1.3394],
        [-1.4021, -0.2137, -1.4021, -0.2137, -1.4021, -0.2137],
        [-1.4021, -0.2137, -1.4021, -0.2137, -0.8702,  2.3228],
        [-1.4021, -0.2137, -0.8702,  2.3228,  0.0471,  0.4526],
        [-0.8702,  2.3228,  0.0471,  0.4526,  0.1257,  0.9819],
        [ 0.0471,  0.4526,  0.1257,  0.9819, -1.4675, -0.3574],
        [ 0.1257,  0.9819, -1.4675, -0.3574,  0.1257,  0.9819],
        [-1.4675, -0.3574,  0.1257,  0.9819,  1.2435, -1.3394],
        [-1.4021, -0.2137, -1.4021, -0.2137, -1.4021, -0.2137],
        [-1.4021, -0.2137, -1.4021, -0.2137,  1.2435, -1.3394],
        [-1.4021, -0.2137,  1.2435, -1.3394, -1.4675, -0.3574],
        [ 1.2435, -1.3394, -1.4675, -0.3

In [65]:
len(torch.unbind(emb, 1))

3

In [67]:
torch.cat(torch.unbind(emb, 1),1)

tensor([[-1.4021, -0.2137, -1.4021, -0.2137, -1.4021, -0.2137],
        [-1.4021, -0.2137, -1.4021, -0.2137,  0.5353,  1.1650],
        [-1.4021, -0.2137,  0.5353,  1.1650, -0.1089, -0.7523],
        [ 0.5353,  1.1650, -0.1089, -0.7523, -0.1089, -0.7523],
        [-0.1089, -0.7523, -0.1089, -0.7523,  1.2435, -1.3394],
        [-1.4021, -0.2137, -1.4021, -0.2137, -1.4021, -0.2137],
        [-1.4021, -0.2137, -1.4021, -0.2137, -0.8702,  2.3228],
        [-1.4021, -0.2137, -0.8702,  2.3228,  0.0471,  0.4526],
        [-0.8702,  2.3228,  0.0471,  0.4526,  0.1257,  0.9819],
        [ 0.0471,  0.4526,  0.1257,  0.9819, -1.4675, -0.3574],
        [ 0.1257,  0.9819, -1.4675, -0.3574,  0.1257,  0.9819],
        [-1.4675, -0.3574,  0.1257,  0.9819,  1.2435, -1.3394],
        [-1.4021, -0.2137, -1.4021, -0.2137, -1.4021, -0.2137],
        [-1.4021, -0.2137, -1.4021, -0.2137,  1.2435, -1.3394],
        [-1.4021, -0.2137,  1.2435, -1.3394, -1.4675, -0.3574],
        [ 1.2435, -1.3394, -1.4675, -0.3

In [68]:
emb.view(32,6)

tensor([[-1.4021, -0.2137, -1.4021, -0.2137, -1.4021, -0.2137],
        [-1.4021, -0.2137, -1.4021, -0.2137,  0.5353,  1.1650],
        [-1.4021, -0.2137,  0.5353,  1.1650, -0.1089, -0.7523],
        [ 0.5353,  1.1650, -0.1089, -0.7523, -0.1089, -0.7523],
        [-0.1089, -0.7523, -0.1089, -0.7523,  1.2435, -1.3394],
        [-1.4021, -0.2137, -1.4021, -0.2137, -1.4021, -0.2137],
        [-1.4021, -0.2137, -1.4021, -0.2137, -0.8702,  2.3228],
        [-1.4021, -0.2137, -0.8702,  2.3228,  0.0471,  0.4526],
        [-0.8702,  2.3228,  0.0471,  0.4526,  0.1257,  0.9819],
        [ 0.0471,  0.4526,  0.1257,  0.9819, -1.4675, -0.3574],
        [ 0.1257,  0.9819, -1.4675, -0.3574,  0.1257,  0.9819],
        [-1.4675, -0.3574,  0.1257,  0.9819,  1.2435, -1.3394],
        [-1.4021, -0.2137, -1.4021, -0.2137, -1.4021, -0.2137],
        [-1.4021, -0.2137, -1.4021, -0.2137,  1.2435, -1.3394],
        [-1.4021, -0.2137,  1.2435, -1.3394, -1.4675, -0.3574],
        [ 1.2435, -1.3394, -1.4675, -0.3

In [70]:
W1 = torch.randn((6,100))
b1 = torch.randn(100)
h = torch.tanh(emb.view(32,6) @ W1 + b1)
h


tensor([[ 0.5893, -0.8772, -0.9968,  ...,  0.9756, -0.9556,  0.9988],
        [ 0.7685, -0.5784,  0.9583,  ...,  0.5987, -0.8444,  0.9948],
        [ 0.9571, -0.9273,  0.9995,  ...,  0.7716, -0.8719, -0.5525],
        ...,
        [ 0.9997,  0.9670, -0.9967,  ...,  0.9901, -0.7767, -0.3009],
        [-0.9074,  0.5289, -0.9989,  ...,  0.7581,  0.3543,  0.9995],
        [ 0.1535, -0.9756,  1.0000,  ...,  0.8846, -0.7275, -0.9780]])

In [71]:
g = torch.Generator().manual_seed(2147483647)
C = torch.randn((27,2), generator=g)
W1 = torch.randn((6,100), generator=g)
b1 = torch.randn(100,generator = g)
W2 = torch.randn((100,27), generator = g)
b2 = torch.randn(27, generator=g)
parameters = [C, W1, b1, W2, b2]

In [72]:
sum(p.nelement() for p in parameters)

3481

In [ ]:
emb = C[X]